スクリプトをなんとかしましたよ(・o・)その2

diff --git a/scripts/python b/scripts/python
--- a/scripts/python
+++ b/scripts/python
@@ -2,20 +2,43 @@
 
 set -eu
 
-function print_usage() {
+test -r "$(dirname $0)/subr.sh" && source "$(dirname $0)/subr.sh"
+
+function print_usage()
+{
     echo "Usage: $0 {install|update|uninstall}" 1>&2
-    echo
 }
 
-function install_packages() {
+function setup_pip()
+{
+    if ! which curl >/dev/null 2>&1
+    then
+        err "curl not found."
+        return 1
+    fi
+    if ! getpython >/dev/null 2>&1
+    then
+        err "python not found."
+        return 1
+    fi
+    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
+    $(getpython) get-pip.py --user
+    export PATH="$($(getpython) -m site --user-base)/bin":$PATH
+    return 0
+}
+
+function install_packages()
+{
     $1 install --user virtualenv
 }
 
-function update_packages() {
+function update_packages()
+{
     $1 list --user --outdated --format=json | jq -r '.[].name' | xargs $1 install --user --upgrade
 }
 
-function uninstall_packages() {
+function uninstall_packages()
+{
     $1 list --user --format=json | jq -r '.[].name' | xargs $1 uninstall -y
 }
 
@@ -31,21 +54,21 @@ then
 elif type pip >/dev/null 2>&1
 then
     pipcmd=pip
-else
-    echo 'pip command required.'
-    exit 2
+else setup_pip
+    err "pip command required."
+    exit 1
 fi
 
 if ! type jq >/dev/null 2>&1
 then
-    echo 'jq command required.'
-    exit 2
+    err "jq command required."
+    exit 1
 fi
 
 if ! type xargs >/dev/null 2>&1
 then
-    echo 'xargs command required.'
-    exit 2
+    err "xargs command required."
+    exit 1
 fi
 
 if [ "$1" = "install" ]
